dependencies:
  flutter:
    sdk: flutter
  tflite: ^1.0.0
  image_picker: ^0.8.4+4
  camera: ^0.9.4+5
  flutter_tts: ^3.2.2
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/model.tflite
    - assets/labels.txt

environment:
  sdk: ">=2.12.0 <3.0.0"

name: color_detection_app 